---
- name: Setup mox as email server
  hosts: your_host 
  vars_files: 
    - ../ansible-playbooks/var_files/secrets/mox.yaml
  vars:
    mox_domain: "yourdomain.com"
    mox_mail_hostname: "mail.yourdomain.com"
    mox_public_ip: "x.x.x.x"
    mox_default_account: "you"
    mox_mta_sts_policy_version_id: "20231133323206"

  roles: 
    - role: nginx-certbot 
      vars:
        nginx_certbot_server_name: "autoconfig.{{ mox_domain }}"
    - role: nginx-certbot 
      vars:
        nginx_certbot_server_name: "mta-sts.{{ mox_domain }}"
    - role: nginx-certbot 
      vars:
        nginx_certbot_server_name: "{{ mox_mail_hostname }}"
    #I don't know how to loop 1 role through a list of var :| 

    - role: mox
      tags: mox