---
- name: Install necessary packages
  apt:
    update_cache: no
    state: latest
    pkg:
      - nginx
      - python3-certbot-nginx

- name: Install custom nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx


- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ nginx_server_name }}/cert.pem"
  register: letsencrypt_cert

- name: Install vhost nginx config
  template:
    src: sample.conf.j2
    dest: "{{ nginx_conf_d }}/{{ nginx_server_name }}.conf"
    mode: '0644'
    owner: root
    group: root
  notify: reload nginx
  when: not letsencrypt_cert.stat.exists

- name: run certbot 
  shell: |
    certbot --nginx -d {{ nginx_server_name }}
  when: not letsencrypt_cert.stat.exists
