---
- name: Install necessary packages
  apt:
    update_cache: no
    state: latest
    pkg:
      - nginx
      - snapd
  become: true

- name: Install cerbot
  shell:
    cmd: snap install --classic certbot
  become: true

- name: Install custom nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx
  become: true

- name: Call generate task
  include_tasks: ./generate_cert.yaml
  loop: "{{ nginx_certbot_server_names }}"

